# Generated by Django 6.0.6 on 2026-07-10 11:17

from django.db import migrations, models


def create_demo_parking_spots(apps, schema_editor):
    parking_spot = apps.get_model('spots', 'ParkingSpot')

    for number in range(1, 51):
        parking_spot.objects.get_or_create(
            number=f'P-{number:03d}',
            defaults={
                'description': 'Демо-место для тестового показа',
                'is_active': True,
            },
        )


def delete_demo_parking_spots(apps, schema_editor):
    parking_spot = apps.get_model('spots', 'ParkingSpot')
    parking_spot.objects.filter(number__in=[f'P-{number:03d}' for number in range(1, 51)]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.RunPython(create_demo_parking_spots, delete_demo_parking_spots),
    ]
