# Generated by Django 6.0.6 on 2026-07-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'ordering': ('number',)},
        ),
    ]
