# Generated by Django 6.0.6 on 2026-07-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
