# Generated by Django 6.0.6 on 2026-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_alter_parkingspot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
