# Generated by Django 6.0.6 on 2026-07-12 20:19

import bookings.models
import django.contrib.postgres.constraints
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_updated_at_reminder_updated_at'),
        ('spots', '0003_parkingspot_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'active')), expressions=[('parking_spot', '='), (bookings.models.TsRange(bookings.models.DateTimeCombine('date', 'start_time'), bookings.models.DateTimeCombine('date', 'end_time')), '&&')], name='exclude_overlapping_active_bookings'),
        ),
    ]
